[pytest]
minversion = 7.0
addopts = -q
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning
    ignore:.*bcrypt.*:UserWarning
    ignore:.*passlib.*:UserWarning
    ignore::sqlalchemy.exc.SAWarning
